[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
numReplicas = 1
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 60
startCommand = "npm run deploy"

[[deploy.healthcheck]]
path = "/api/health"
interval = 90
timeout = 30
